name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore BusBus.sln
      - name: Build
        run: dotnet build BusBus.sln --configuration Release --no-restore
      - name: Test with Coverage
        run: dotnet test BusBus.sln --verbosity minimal --logger "console;verbosity=minimal"
      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: '**/*.trx'
        if: always()