name: BusBus Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  test:
    runs-on: self-hosted
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true

      - name: Restore dependencies
        run: dotnet restore BusBus.sln --verbosity normal

      - name: Build solution
        run: dotnet build BusBus.sln --configuration Release --no-restore

      - name: Run tests with coverage
        id: test-step
        run: |
          dotnet test BusBus.sln --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory TestResults --logger "trx;LogFileName=test-results.trx" --verbosity normal
        continue-on-error: true

      - name: Process test results
        id: process-results
        if: always()
        shell: pwsh
        run: |
          Write-Host "Checking for test result files..."

          if (-not (Test-Path "TestResults")) {
            Write-Warning "TestResults directory not found. Creating it..."
            New-Item -ItemType Directory -Path "TestResults" -Force
          }

          $testResultFiles = Get-ChildItem -Path "TestResults" -Filter "*.trx" -Recurse -ErrorAction SilentlyContinue
          $totalTests = 0
          $passedTests = 0
          $failedTests = 0

          if ($testResultFiles.Count -eq 0) {
            Write-Warning "No test result files found in TestResults directory."
            Write-Host "Directory contents:"
            Get-ChildItem -Path "TestResults" -Recurse | ForEach-Object { Write-Host "  $($_.FullName)" }

            echo "total_tests=0" >> $env:GITHUB_OUTPUT
            echo "passed_tests=0" >> $env:GITHUB_OUTPUT
            echo "failed_tests=0" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "Found $($testResultFiles.Count) test result file(s)"
            foreach ($file in $testResultFiles) {
              try {
                Write-Host "Processing: $($file.FullName)"
                [xml]$xml = Get-Content $file.FullName
                $counters = $xml.TestRun.ResultSummary.Counters
                $totalTests += [int]$counters.total
                $passedTests += [int]$counters.passed
                $failedTests += [int]$counters.failed
              } catch {
                Write-Warning "Failed to parse test result file: $($file.FullName) - $($_.Exception.Message)"
              }
            }

            Write-Host "Test Summary: $passedTests passed, $failedTests failed (of $totalTests total)"
            echo "total_tests=$totalTests" >> $env:GITHUB_OUTPUT
            echo "passed_tests=$passedTests" >> $env:GITHUB_OUTPUT
            echo "failed_tests=$failedTests" >> $env:GITHUB_OUTPUT
          }

      - name: Generate coverage report
        if: always()
        shell: pwsh
        run: |
          Write-Host "Setting up coverage reporting..."

          try {
            dotnet tool install -g dotnet-reportgenerator-globaltool --ignore-failed-sources
          } catch {
            Write-Host "ReportGenerator might already be installed"
          }

          $coverageFiles = Get-ChildItem -Path "TestResults" -Filter "coverage.cobertura.xml" -Recurse -ErrorAction SilentlyContinue

          if ($coverageFiles.Count -gt 0) {
            Write-Host "Found $($coverageFiles.Count) coverage file(s)"

            New-Item -ItemType Directory -Path "TestResults/CoverageReport" -Force

            try {
              reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:TestResults/CoverageReport -reporttypes:Html,Cobertura,TextSummary

              if (Test-Path "TestResults/CoverageReport/Summary.txt") {
                Write-Host "Coverage Summary:"
                Get-Content "TestResults/CoverageReport/Summary.txt"
              } else {
                Write-Warning "Summary.txt not generated"
              }
            } catch {
              Write-Warning "Failed to generate coverage report: $($_.Exception.Message)"
            }
          } else {
            Write-Warning "No coverage files found."
            Write-Host "TestResults directory contents:"
            Get-ChildItem -Path "TestResults" -Recurse -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "  $($_.FullName)" }

            New-Item -ItemType Directory -Path "TestResults/CoverageReport" -Force
            "No coverage data available" | Out-File -FilePath "TestResults/CoverageReport/no-coverage.txt"
          }

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults/
          retention-days: 30
          if-no-files-found: warn

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: TestResults/CoverageReport/
          retention-days: 30
          if-no-files-found: warn

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: TestResults/**/*.trx
          check_name: "Test Results"
          comment_mode: create new
          job_summary: true

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request' && always()
        uses: 5monkeys/cobertura-action@master
        with:
          path: TestResults/CoverageReport/Cobertura.xml
          minimum_coverage: 75
          fail_below_threshold: false
        continue-on-error: true

      - name: Report summary
        if: always()
        shell: pwsh
        run: |
          $summary = @"
          ### 🧪 Test Results Summary

          - ✅ **Passed**: ${{ steps.process-results.outputs.passed_tests || 0 }}
          - ❌ **Failed**: ${{ steps.process-results.outputs.failed_tests || 0 }}
          - 📊 **Total**: ${{ steps.process-results.outputs.total_tests || 0 }}

          "@

          if (Test-Path "TestResults/CoverageReport/Summary.txt") {
            $summary += "`n### 📈 Code Coverage`n`n"
            $summary += "``````text`n"
            $summary += Get-Content "TestResults/CoverageReport/Summary.txt" -Raw
            $summary += "`n``````"
          } else {
            $summary += "`n### 📈 Code Coverage`n`nNo coverage data available."
          }

          $summary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8

          Write-Host "::notice::Check the uploaded artifacts for detailed test and coverage reports"

          $failedTests = [int]"${{ steps.process-results.outputs.failed_tests || 0 }}"
          $totalTests = [int]"${{ steps.process-results.outputs.total_tests || 0 }}"

          if ($totalTests -eq 0) {
            Write-Host "::warning::No tests were found or executed. Check your test project configuration."
          } elseif ($failedTests -gt 0) {
            Write-Host "::error::$failedTests test(s) failed out of $totalTests total"
            exit 1
          } else {
            Write-Host "::notice::All $totalTests tests passed successfully!"
          }
